timeArrange/timeArrange/config/routes.rb
Timetable::Application.routes.draw do
  get "teacher/index"

  root :to => 'login#index'
  
  match "/login" => "login#index", :as => "login"
  match "/login/verify" => "login#verify", :as => "login_verify", :via => :post
  match "/logout" => "login#destroy", :as => "logout"
   
  match "/admin" => "admin#index", :as => "admin"
  match "/admin/new_teacher" => "teacher#new_teacher", :as => "admin_new_teacher"
  match "/admin/save_teacher" => "teacher#save_teacher", :as => "admin_save_teacher", :via => :post
  match "/admin/edit_teacher/show" => "teacher#edit_teacher", :as => "admin_show_edit_teacher"
  match "/admin/edit_teacher/:id" => "teacher#edit_teacher", :as => "admin_edit_teacher"
  match "/admin/delete_teacher/:id" => "teacher#delete_teacher", :as => "admin_delete_teacher"
  
  match "/admin/edit_timesheet" => "timesheets#edit", :as => "admin_edit_timesheet"
  match "/admin/save_timesheet" => "timesheets#save", :as => "admin_save_timesheet"
  match "/admin/timesheet" => "timesheets#index", :as => "admin_timesheet"
  
  match "/teacher" => "teacher#index", :as => "teacher"
  match "/teacher/timesheet/:id" => "timesheets#index", :as => "teacher_timesheet"
  
  resources :users, :courses, :course_types, :hours, :teaches, :roles, :wishes, :timesheets

end

timeArrange/timeArrange/app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :hour
end
 

timeArrange/timeArrange/app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  respond_to :html, :xml, :json
  before_filter :authenticate_for_admin, :only => [:save, :edit]

  def index
    load_data
    
    @timesheets = Timesheet.order('start_time ASC').all

    @time_table_cells = []
    @timesheets.each_with_index do |timesheet, i|
      hour_id = params["cell_" + i.to_s] 
      hour = Hour.where(:id => hour_id).first
      unless hour.nil?
        teach = hour.teach
        unless teach.nil?
          unless params[:id].nil?
            if teach.user_id.to_i == params[:id].to_i
              @time_table_cells[i] = hour.course_type.name.to_s + " - " + teach.course.title
            else
              @time_table_cells[i] = ""
            end
          else
            @time_table_cells[i] = hour.course_type.name.to_s + " - " + teach.course.title
          end
        else
          @time_table_cells[i] = ""
        end
      else
        @time_table_cells[i] = ""
      end
      
    end
  end
  
  def edit
    load_data  
  end

  def save
    unless params[:modified_cell_id].nil?
      hour_id = params[params[:modified_cell_id]]

      if hour_id.to_s != " "
        hour = Hour.where(:id => hour_id).first
        
        unless hour.nil?
          cell_id = params[:modified_cell_id].match(/\d*$/)[0].to_i
          
          start_time = (8 + (cell_id % 6 * 2) + 24 * (cell_id / 6)) * 3600
          timesheet = Timesheet.where(:start_time => Time.at(start_time).gmtime).first
          
          unless timesheet.nil?
            hour.timesheet = timesheet
            timesheet.hour = hour
            hour.save
            timesheet.save
          end
        end
      else
        cell_id = params[:modified_cell_id].match(/\d*$/)[0].to_i
        start_time = (8 + (cell_id % 6 * 2) + 24 * (cell_id / 6)) * 3600
        timesheet = Timesheet.where(:start_time => Time.at(start_time).gmtime).first

        unless timesheet.nil?
          hour = timesheet.hour
          unless hour.nil?
            hour.timesheet = nil
            hour.save
          end
          timesheet.hour = nil
          timesheet.save
        end
      end
    end
    
    load_data
    
    respond_with do |format|
      format.html do 
        if request.xhr?
           render :partial => "timesheets/edit_timetable", :locals => {:all_grouped_options => @all_grouped_options, :params => params}
        else
          render "index"
        end
      end
    end
  end

  private
  def load_data
    @timesheets = Timesheet.order('start_time ASC').all
    
    @all_grouped_options = []
    
    @timesheets.each_with_index do |timesheet, i|
      params["cell_" + i.to_s] = " "
    end
    
    hours_assigned = []
    unassigned_grouped_options = {"" => [" "]}
    @teaches = Teach.all
    @teaches.each do |teach|
      unless teach.course.nil?
        teach.hours.each do |hour|
          if hour.hours != Time.at(0).gmtime
            if unassigned_grouped_options[teach.course.title].nil?
              unassigned_grouped_options[teach.course.title] = []
            end
            
            unless hour.timesheet.nil?
              hours_assigned << hour
              
              time = Time.at(hour.timesheet.start_time).gmtime
              cell_index = (time.day - 1) * 6 + (time.hour - 8) / 2
              cell_id = "cell_" + cell_index.to_s
              params[cell_id] = hour.id
            end
            
            unless hours_assigned.include? hour
              unassigned_grouped_options[teach.course.title] << [hour.course_type.name.to_s + " - " + teach.course.title, hour.id]
            end
          end
        end
      end
    end
    
    @timesheets.each_with_index do |timesheet, i|
      @all_grouped_options[i] = Marshal.load(Marshal.dump(unassigned_grouped_options))
      if params["cell_" + i.to_s].to_s != " "
        hour_id = params["cell_" + i.to_s]
        hour = Hour.where(:id => hour_id).first
        unless hour.nil?
          teach = hour.teach
          @all_grouped_options[i][teach.course.title] << [hour.course_type.name.to_s + " - " + teach.course.title, hour.id]
        end
      end
    end
  end

end

timeArrange/timeArrange/app/helpers/timesheets_helper.rb
module TimesheetsHelper
end
 

timeArrange/timeArrange/app/views/timesheets/_edit_timetable.html.erb
<%= form_tag admin_save_timesheet_path, :remote => true, :id => 'timesheet_table_form' do %>
<table style="margin-left: auto; margin-right: auto; width: 90%;">
	<tr style="background-color: white;">
		<th style="width: 50px;"><%= t(:hour)%></th>
		<th><%= t(:monday)%></th>
		<th><%= t(:tuesday)%></th>
		<th><%= t(:wednesday)%></th>
		<th><%= t(:thursday)%></th>
		<th><%= t(:friday)%></th>
	</tr>
	<% 6.times do |i|%>
	<tr <%= "style='background-color:" + ((i % 2 == 0) ? "#ccc;'" : "#ddd'") %> >
		<td style="text-align: center;">
			<%= 8 + (i*2) %>:00
		</td>
		<% 5.times do |j| 
			count = j*6 + i
			cell_id = "cell_" + count.to_s
			selected = params[cell_id] unless params.nil?
			submit_form = "submit_form('" + cell_id.to_s + "')"
		%>
			<td style="text-align: center;">
				<%= select_tag cell_id, grouped_options_for_select(all_grouped_options[count], selected), :style => "width: 200px;", :onchange => submit_form %>
			</td>			
		<% end %>
	</tr> 
	<% end %>
</table>
<%= submit_tag "Submit", :name => :save_timesheet, :id => :save_timesheet_submit_button, :style => "visibility: hidden; width: 0px; height: 1px;" %>
<% end %>

timeArrange/timeArrange/app/views/timesheets/_form.html.erb
<%= form_for(@timesheet) do |f| %>
  <% if @timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
      <% @timesheet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :repeats %><br />
    <%= f.number_field :repeats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

timeArrange/timeArrange/app/views/timesheets/_show_timetable.html.erb
<table style="margin-left: auto; margin-right: auto; width: 90%;">
	<tr style="background-color: white;">
		<th style="width: 50px;"><%= t(:hour)%></th>
		<th><%= t(:monday)%></th>
		<th><%= t(:tuesday)%></th>
		<th><%= t(:wednesday)%></th>
		<th><%= t(:thursday)%></th>
		<th><%= t(:friday)%></th>
	</tr>
	<% 6.times do |i|%>
	<tr <%= "style='background-color:" + ((i % 2 == 0) ? "#ccc;'" : "#ddd'") %> >
		<td style="text-align: center;">
			<%= 8 + (i*2) %>:00
		</td>
		<% 5.times do |j| 
			count = j*6 + i
			cell_id = "cell_" + count.to_s
			selected = params[cell_id] unless params.nil?
			submit_form = "submit_form('" + cell_id.to_s + "')"
		%>
			<td style="text-align: center;">
				<%= time_table_cells[count] %>
			</td>			
		<% end %>
	</tr>
	<% end %>
</table> 

timeArrange/timeArrange/app/views/timesheets/edit.html.erb
<h1 style="text-align: center;"><%= t(:edit_timesheet)%></h1>

<div id="form_container">
	
<%= render :partial => "timesheets/edit_timetable", :locals => {:all_grouped_options => @all_grouped_options, :params => params } %>

</div>
 

timeArrange/timeArrange/app/views/timesheets/index.html.erb
<h1 style="text-align: center;"><%= t(:timesheet)%></h1>

<%= render :partial => "timesheets/show_timetable", :locals => {:time_table_cells => @time_table_cells} %>
 

timeArrange/timeArrange/app/views/timesheets/new.html.erb
<h1>New timesheet</h1>

<%= render 'form' %>

<%= link_to 'Back', timesheets_path %>
 

timeArrange/timeArrange/app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start time:</b>
  <%= @timesheet.start_time %>
</p>

<p>
  <b>Repeats:</b>
  <%= @timesheet.repeats %>
</p>


<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>
 